before:
  hooks:

builds:
  -
    id: build
    main: ./cmd/git-clone
    binary: git-clone
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s
      - -w
      - -X github.com/gertd/git-clone/pkg/version.ver={{.Version}}
      - -X github.com/gertd/git-clone/pkg/version.commit={{.ShortCommit}}
      - -X github.com/gertd/git-clone/pkg/version.date={{.Date}}
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - format: zip
    rlcp: true
    files:
      - LICENSE
      - README.md
    name_template: >-
      git-clone-{{ .Version }}_{{ .Os }}_{{- if eq .Arch "amd64" }}x86_64{{- else }}{{ .Arch }}{{ end }}


checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: gertd
    name: git-clone

  draft: false
  prerelease: false
  name_template: "git-clone {{.Tag}}"

brews:
  - name: git-clone

    tap:
      owner: gertd
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP }}"

    url_template: "https://github.com/gertd/git-clone/releases/download/{{ .Tag }}/{{ .ArtifactName }}"

    commit_author:
      name: Gert Drapers
      email: gert-bot@d5s.io

    homepage: "https://github.com/gertd/git-clone"

    description: "git-clone CLI"

    license: "MIT"

    skip_upload: false

    test: |
      system "#{bin}/git-clone version"

    install: |
      bin.install "git-clone"

publishers:
  - name: oras
    dir: "{{ dir .ArtifactPath }}"
    cmd: | 
      oras push -u {{ .Env.DOCKER_USERNAME }} -p {{ .Env.DOCKER_PASSWORD }} \
      ghcr.io/gertd/git-clone_{{ .Os }}_{{ .Arch }}:{{ .Tag }} \
      --artifact-type  application/vnd.unknown.layer.v1+txt \
      build_{{ .Os }}_{{- if eq .Arch "amd64" }}amd64_v1{{- else }}{{ .Arch }}{{ end }}/git-clone{{- if eq .Arch "windows" }}.exe{{ end }}
